---
- hosts: all
  sudo: yes

  vars:
    docker_version: 1.6.0

  roles:
    - docker

    - role: cassandra-docker
      master: true
      node_name: quietnessdb-master

    - role: cassandra-docker
      master: false
      node_name: quietnessdb-node1

    - role: cassandra-docker
      master: false
      node_name: quietnessdb-node2

    - role: quietness
      cassandra_master: quietnessdb-master
      repository_version: master