- name: add nodejs ppa
  command: add-apt-repository -y ppa:chris-lea/node.js
    creates=/etc/apt/sources.list.d/chris-lea-node_js-precise.list

- name: ensure compass is installed
  apt: pkg=ruby-compass state=latest update_cache=yes

- name: ensure nodejs is installed
  apt: pkg=nodejs state=latest update_cache=yes

- name: install global node dependencies
  command: npm install -g {{ item.key }}
    creates={{ item.value }}
  with_dict:
      bower: "/usr/bin/bower"
      less: "/usr/bin/lessc"
      recess: "/usr/bin/recess"
      coffee-script: "/usr/bin/coffee"


- name: install compass
  command: gem install compass
