- name: copying code over
  copy: src="." dest=/srv/quietness

- name: setup quietness api in upstart
  template: src=quietness-docker.upstart dest=/etc/init/quietnessapi.conf
    owner=root group=root mode=644

- name: build quietness docker image
  command: docker build -t quietnessapi .
  args:
    chdir: /srv/quietness/timeless

- name: start quietness api
  service: name=quietnessapi
    state=restarted
