- name: copying code over
  synchronize: src="{{ role_path }}/../../" dest=/srv/quietness archive=no links=yes

- name: setup quietness api in upstart
  template: src=quietness-docker.upstart dest=/etc/init/quietness-api.conf
    owner=root group=root mode=644

- name: build quietness docker image
  docker:
    #docker_api_version: 1.6.0
    name: quietness-api
    image: /srv/quietness
    state: present
    volumes:
    - /srv/quietness

- name: start quietness api
  service: name=quietness-api
    state=restarted
